version: '3.3'
services:
  jumpstarter:
    build: .
    network_mode: host
    volumes:
      - ~/.ssh/:/root/.ssh/
            #      - ~/.ssh/:/.ssh/
    environment:
      - GIT_CLUSTER="git@github.com:trumandk/cluster.git"
